---
# tasks file for odoo

- name: install ubuntu packages
  apt:    
    name:
      - build-essential
      - git      
      - virtualenv
      - pipenv
      - poppler-utils
      - bzip2      
      - curl      
      - fonts-freefont-ttf
      - fonts-ubuntu
      - fontconfig
      - python3-dev
      - libcairo2-dev
      - libcups2-dev      
      - libffi-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libssl-dev
      - libldap-dev
      - libxml2-dev
      - libxslt1-dev
      - libpq-dev
      - libhttp-parser-dev
      - libsasl2-dev
      - libmagickwand-dev
    state: present

- name: copy imagemagick policy
  copy:
    src: files/ImageMagick-6/policy.xml
    dest: /etc/ImageMagick-6/policy.xml

- name: get odoo source
  git:
    repo: {{ odoo_repo }}
    dest: {{ odoo_dir }}
    version: {{ odoo_version }}
  register: odoo_update

- name: update python environment
  become_user: "{{ odoo_user }}"
  become: yes
  when: odoo_update
  shell: pipenv update
  tags: 
  - full
  args:
    chdir: {{ odoo_dir }}
  
- name: check if ~/.local/etc exist
  become_user: "{{ odoo_user }}"
  become: yes
  file:    
    path: "{{ odoo_user_home }}/.local/etc"
    recurse: yes
    state: directory

- name: check if ~/log exist
  become_user: "{{ odoo_user }}"
  become: yes
  file:    
    path: "{{ odoo_user_home }}/odoo/log"
    recurse: yes
    state: directory

- name: copy odoo service config
  become_user: "{{ odoo_user }}"
  become: yes
  template:
    src: templates/odoo.conf
    dest: "{{ odoo_user_home }}/.local/etc/{{ odoo_service }}.conf"
        
- name: copy odoo-cron service config
  become_user: "{{ odoo_user }}"
  become: yes
  template:
    src: templates/odoo-cron.conf
    dest: "{{ odoo_user_home }}/.local/etc/{{ odoo_service }}-cron.conf"
    
- name: copy odoo service
  template:
    src: files/odoo.service
    dest: /etc/systemd/system/{{ odoo_service }}.service

- name: copy odoo cron-service
  template:
    src: files/odoo-cron.service
    dest: /etc/systemd/system/{{ odoo_service }}-cron.service