---
# handlers file for odoo

- name: install modules
  become_user: odoo
  when: odoo_update|bool
  become: yes
  shell: pipenv run ./odoo-bin install
  args:
    chdir: /home/odoo/odoo-oerp-14.0/odoo  
  listen: "update-odoo"

- name: update databases 
  become_user: odoo
  when: odoo_update|bool and not odoo_cluster|bool
  become: yes
  shell: pipenv run ./odoo-bin update -dc /home/odoo/.local/etc/odoo.conf
  args:
    chdir: /home/odoo/odoo-oerp-14.0/odoo
  listen: "update-odoo"

- name: update databases for cluster
  become_user: odoo
  when: odoo_update|bool and odoo_cluster|bool
  become: yes
  shell: pipenv run ./odoo-bin update --db-all -dc /home/odoo/.local/etc/odoo.conf
  args:
    chdir: /home/odoo/odoo-oerp-14.0/odoo
  async: 3600
  poll: 5
  listen: "update-odoo"

- name: start odoo service
  systemd: 
    state: started 
    name: odoo 
    daemon_reload: yes
    enabled: yes
  listen: "update-odoo"

- name: start odoo-cron service
  when: odoo_workers|int > 0
  systemd: 
    state: started 
    name: odoo-cron 
    daemon_reload: yes
    enabled: yes
  listen: "update-odoo"

- name: disable odoo-cron service
  when: odoo_workers|int <= 0
  systemd: 
    state: stopped     
    name: odoo-cron 
    daemon_reload: yes
    enabled: no
  listen: "update-odoo"

- name: restart odoo  
  systemd: 
    state: restarted
    name: odoo
  listen: "update-odoo"
       
- name: restart odoo-cron
  when: odoo_workers|int > 0
  systemd: 
    state: restarted
    name: odoo-cron
  listen: "update-odoo"